//*
// Indicates the type of source address for the Bluetooth device.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/bluetooth/addresstype/address_type.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressType int32

const (
	AddressType_UNKNOWN   AddressType = 0 // Address type is unknown or unavailable
	AddressType_PUBLIC    AddressType = 1 // Hardware MAC Address of the device
	AddressType_RANDOM    AddressType = 2 // Address is either resolvable, non-resolvable or static.
	AddressType_ANONYMOUS AddressType = 3 // Address type used to indicate an anonymous advertisement.
)

// Enum value maps for AddressType.
var (
	AddressType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PUBLIC",
		2: "RANDOM",
		3: "ANONYMOUS",
	}
	AddressType_value = map[string]int32{
		"UNKNOWN":   0,
		"PUBLIC":    1,
		"RANDOM":    2,
		"ANONYMOUS": 3,
	}
)

func (x AddressType) Enum() *AddressType {
	p := new(AddressType)
	*p = x
	return p
}

func (x AddressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_enumTypes[0].Descriptor()
}

func (AddressType) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_enumTypes[0]
}

func (x AddressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressType.Descriptor instead.
func (AddressType) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_bluetooth_addresstype_address_type_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74,
	0x68, 0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x2b, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74,
	0x68, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x41, 0x0a,
	0x0b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x55, 0x42,
	0x4c, 0x49, 0x43, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x41, 0x4e, 0x44, 0x4f, 0x4d, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x4e, 0x4f, 0x4e, 0x59, 0x4d, 0x4f, 0x55, 0x53, 0x10, 0x03,
	0x42, 0x3a, 0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f,
	0x6f, 0x74, 0x68, 0x50, 0x01, 0x5a, 0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDescData = file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDesc
)

func file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDescData)
	})
	return file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDescData
}

var file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_goTypes = []any{
	(AddressType)(0), // 0: com.craxiom.messaging.bluetooth.addresstype.AddressType
}
var file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_init() }
func file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_init() {
	if File_com_craxiom_messaging_bluetooth_addresstype_address_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_bluetooth_addresstype_address_type_proto = out.File
	file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_rawDesc = nil
	file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_goTypes = nil
	file_com_craxiom_messaging_bluetooth_addresstype_address_type_proto_depIdxs = nil
}
