//*
// Defines the connection handshake sequence for validating a connection to a Network Survey Messaging server.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/grpc/connection_handshake.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A connection request that should be sent out by the client to initiate the connection to the server.
type ConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_craxiom_messaging_grpc_connection_handshake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_com_craxiom_messaging_grpc_connection_handshake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescGZIP(), []int{0}
}

// The response from the server for the connection request.
//
// connection_accept:  True if the connection is accepted, false otherwise.
type ConnectionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectionAccept bool `protobuf:"varint,1,opt,name=connectionAccept,proto3" json:"connectionAccept,omitempty"`
}

func (x *ConnectionReply) Reset() {
	*x = ConnectionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_com_craxiom_messaging_grpc_connection_handshake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionReply) ProtoMessage() {}

func (x *ConnectionReply) ProtoReflect() protoreflect.Message {
	mi := &file_com_craxiom_messaging_grpc_connection_handshake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionReply.ProtoReflect.Descriptor instead.
func (*ConnectionReply) Descriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionReply) GetConnectionAccept() bool {
	if x != nil {
		return x.ConnectionAccept
	}
	return false
}

var File_com_craxiom_messaging_grpc_connection_handshake_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDesc = []byte{
	0x0a, 0x35, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61,
	0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x32, 0x86, 0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12,
	0x6f, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x35, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x50, 0x01,
	0x5a, 0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescData = file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDesc
)

func file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescData)
	})
	return file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDescData
}

var file_com_craxiom_messaging_grpc_connection_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_craxiom_messaging_grpc_connection_handshake_proto_goTypes = []any{
	(*ConnectionRequest)(nil), // 0: com.craxiom.messaging.grpc.ConnectionRequest
	(*ConnectionReply)(nil),   // 1: com.craxiom.messaging.grpc.ConnectionReply
}
var file_com_craxiom_messaging_grpc_connection_handshake_proto_depIdxs = []int32{
	0, // 0: com.craxiom.messaging.grpc.ConnectionHandshake.StartConnection:input_type -> com.craxiom.messaging.grpc.ConnectionRequest
	1, // 1: com.craxiom.messaging.grpc.ConnectionHandshake.StartConnection:output_type -> com.craxiom.messaging.grpc.ConnectionReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_grpc_connection_handshake_proto_init() }
func file_com_craxiom_messaging_grpc_connection_handshake_proto_init() {
	if File_com_craxiom_messaging_grpc_connection_handshake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_com_craxiom_messaging_grpc_connection_handshake_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_com_craxiom_messaging_grpc_connection_handshake_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConnectionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_craxiom_messaging_grpc_connection_handshake_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_grpc_connection_handshake_proto_depIdxs,
		MessageInfos:      file_com_craxiom_messaging_grpc_connection_handshake_proto_msgTypes,
	}.Build()
	File_com_craxiom_messaging_grpc_connection_handshake_proto = out.File
	file_com_craxiom_messaging_grpc_connection_handshake_proto_rawDesc = nil
	file_com_craxiom_messaging_grpc_connection_handshake_proto_goTypes = nil
	file_com_craxiom_messaging_grpc_connection_handshake_proto_depIdxs = nil
}
