//*
// Defines the Encryption Type values used in the 802.11 Survey message.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/wifi/encryptiontype/encryption_type.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// This enum defines the Encryption Type field of the 802.11 messages.
//
// Note that the Encryption_Type field should be kept in sync with the Cipher_Suites field.  The two fields are closely related.
// The Encryption_Type field stores the WiFi Alliance coined terms for the various cipher suites.
//
// Following are how the Encryption_Type values
// map to the Cipher_Suites values.
// OPEN     - OPEN
// WEP      - WEP_40 and/or WEP_104
// WPA      - TKIP
// WPA_WPA2 - TKIP and CCMP
// WPA2     - CCMP
type EncryptionType int32

const (
	EncryptionType_UNKNOWN   EncryptionType = 0
	EncryptionType_OPEN      EncryptionType = 1
	EncryptionType_WEP       EncryptionType = 2
	EncryptionType_WPA       EncryptionType = 3
	EncryptionType_WPA_WPA2  EncryptionType = 4
	EncryptionType_WPA2      EncryptionType = 5
	EncryptionType_WPA3      EncryptionType = 6
	EncryptionType_WPA2_WPA3 EncryptionType = 7
)

// Enum value maps for EncryptionType.
var (
	EncryptionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "OPEN",
		2: "WEP",
		3: "WPA",
		4: "WPA_WPA2",
		5: "WPA2",
		6: "WPA3",
		7: "WPA2_WPA3",
	}
	EncryptionType_value = map[string]int32{
		"UNKNOWN":   0,
		"OPEN":      1,
		"WEP":       2,
		"WPA":       3,
		"WPA_WPA2":  4,
		"WPA2":      5,
		"WPA3":      6,
		"WPA2_WPA3": 7,
	}
)

func (x EncryptionType) Enum() *EncryptionType {
	p := new(EncryptionType)
	*p = x
	return p
}

func (x EncryptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_enumTypes[0].Descriptor()
}

func (EncryptionType) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_enumTypes[0]
}

func (x EncryptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionType.Descriptor instead.
func (EncryptionType) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x77, 0x69, 0x66, 0x69, 0x2f, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x29, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x77, 0x69, 0x66, 0x69, 0x2e, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x6a, 0x0a, 0x0e,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4f,
	0x50, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x45, 0x50, 0x10, 0x02, 0x12, 0x07,
	0x0a, 0x03, 0x57, 0x50, 0x41, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x50, 0x41, 0x5f, 0x57,
	0x50, 0x41, 0x32, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x50, 0x41, 0x32, 0x10, 0x05, 0x12,
	0x08, 0x0a, 0x04, 0x57, 0x50, 0x41, 0x33, 0x10, 0x06, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x50, 0x41,
	0x32, 0x5f, 0x57, 0x50, 0x41, 0x33, 0x10, 0x07, 0x42, 0x35, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e,
	0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x2e, 0x77, 0x69, 0x66, 0x69, 0x50, 0x01, 0x5a, 0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f,
	0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDescData = file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDesc
)

func file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDescData)
	})
	return file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDescData
}

var file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_goTypes = []any{
	(EncryptionType)(0), // 0: com.craxiom.messaging.wifi.encryptiontype.EncryptionType
}
var file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_init() }
func file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_init() {
	if File_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto = out.File
	file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_rawDesc = nil
	file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_goTypes = nil
	file_com_craxiom_messaging_wifi_encryptiontype_encryption_type_proto_depIdxs = nil
}
