//*
// Defines the GSM Signaling OTA Channel Type values used in the GSM Signaling message.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/gsmsignalingchanneltype/gsm_signaling_channel_type.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GsmSignalingChannelType int32

const (
	GsmSignalingChannelType_UNKNOWN GsmSignalingChannelType = 0
	GsmSignalingChannelType_BCCH    GsmSignalingChannelType = 1
	GsmSignalingChannelType_CCCH    GsmSignalingChannelType = 2
	GsmSignalingChannelType_RACH    GsmSignalingChannelType = 3
	GsmSignalingChannelType_AGCH    GsmSignalingChannelType = 4
	GsmSignalingChannelType_PCH     GsmSignalingChannelType = 5
	GsmSignalingChannelType_SDCCH   GsmSignalingChannelType = 6
	GsmSignalingChannelType_SDCCH4  GsmSignalingChannelType = 7
	GsmSignalingChannelType_SDCCH8  GsmSignalingChannelType = 8
	GsmSignalingChannelType_TCH_F   GsmSignalingChannelType = 9
	GsmSignalingChannelType_TCH_H   GsmSignalingChannelType = 10
	GsmSignalingChannelType_PACCH   GsmSignalingChannelType = 11
	GsmSignalingChannelType_CBCH52  GsmSignalingChannelType = 12
	GsmSignalingChannelType_PDCH    GsmSignalingChannelType = 13
	GsmSignalingChannelType_PTCCH   GsmSignalingChannelType = 14
	GsmSignalingChannelType_CBCH51  GsmSignalingChannelType = 15
	GsmSignalingChannelType_VOICE_F GsmSignalingChannelType = 16
	GsmSignalingChannelType_VOICE_H GsmSignalingChannelType = 17
)

// Enum value maps for GsmSignalingChannelType.
var (
	GsmSignalingChannelType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "BCCH",
		2:  "CCCH",
		3:  "RACH",
		4:  "AGCH",
		5:  "PCH",
		6:  "SDCCH",
		7:  "SDCCH4",
		8:  "SDCCH8",
		9:  "TCH_F",
		10: "TCH_H",
		11: "PACCH",
		12: "CBCH52",
		13: "PDCH",
		14: "PTCCH",
		15: "CBCH51",
		16: "VOICE_F",
		17: "VOICE_H",
	}
	GsmSignalingChannelType_value = map[string]int32{
		"UNKNOWN": 0,
		"BCCH":    1,
		"CCCH":    2,
		"RACH":    3,
		"AGCH":    4,
		"PCH":     5,
		"SDCCH":   6,
		"SDCCH4":  7,
		"SDCCH8":  8,
		"TCH_F":   9,
		"TCH_H":   10,
		"PACCH":   11,
		"CBCH52":  12,
		"PDCH":    13,
		"PTCCH":   14,
		"CBCH51":  15,
		"VOICE_F": 16,
		"VOICE_H": 17,
	}
)

func (x GsmSignalingChannelType) Enum() *GsmSignalingChannelType {
	p := new(GsmSignalingChannelType)
	*p = x
	return p
}

func (x GsmSignalingChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GsmSignalingChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_enumTypes[0].Descriptor()
}

func (GsmSignalingChannelType) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_enumTypes[0]
}

func (x GsmSignalingChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GsmSignalingChannelType.Descriptor instead.
func (GsmSignalingChannelType) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDesc = []byte{
	0x0a, 0x4e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x73, 0x6d, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x2f,
	0x67, 0x73, 0x6d, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x2d, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x67, 0x73, 0x6d, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x2a,
	0xe2, 0x01, 0x0a, 0x17, 0x47, 0x73, 0x6d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x43, 0x43, 0x48,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x43, 0x43, 0x48, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x52, 0x41, 0x43, 0x48, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x47, 0x43, 0x48, 0x10, 0x04,
	0x12, 0x07, 0x0a, 0x03, 0x50, 0x43, 0x48, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x44, 0x43,
	0x43, 0x48, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x44, 0x43, 0x43, 0x48, 0x34, 0x10, 0x07,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x44, 0x43, 0x43, 0x48, 0x38, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05,
	0x54, 0x43, 0x48, 0x5f, 0x46, 0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x43, 0x48, 0x5f, 0x48,
	0x10, 0x0a, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x41, 0x43, 0x43, 0x48, 0x10, 0x0b, 0x12, 0x0a, 0x0a,
	0x06, 0x43, 0x42, 0x43, 0x48, 0x35, 0x32, 0x10, 0x0c, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x44, 0x43,
	0x48, 0x10, 0x0d, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x54, 0x43, 0x43, 0x48, 0x10, 0x0e, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x42, 0x43, 0x48, 0x35, 0x31, 0x10, 0x0f, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x4f,
	0x49, 0x43, 0x45, 0x5f, 0x46, 0x10, 0x10, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x4f, 0x49, 0x43, 0x45,
	0x5f, 0x48, 0x10, 0x11, 0x42, 0x30, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78,
	0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x50, 0x01, 0x5a,
	0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDescData = file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDesc
)

func file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDescData)
	})
	return file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDescData
}

var file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_goTypes = []any{
	(GsmSignalingChannelType)(0), // 0: com.craxiom.messaging.gsmsignalingchanneltype.GsmSignalingChannelType
}
var file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_init()
}
func file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_init() {
	if File_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto = out.File
	file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_rawDesc = nil
	file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_goTypes = nil
	file_com_craxiom_messaging_gsmsignalingchanneltype_gsm_signaling_channel_type_proto_depIdxs = nil
}
