//*
// Defines the LTE Bandwidth values used in the LTE Survey message.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/ltebandwidth/lte_bandwidth.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LteBandwidth int32

const (
	LteBandwidth_UNKNOWN LteBandwidth = 0
	LteBandwidth_MHZ_1_4 LteBandwidth = 1
	LteBandwidth_MHZ_3   LteBandwidth = 2
	LteBandwidth_MHZ_5   LteBandwidth = 3
	LteBandwidth_MHZ_10  LteBandwidth = 4
	LteBandwidth_MHZ_15  LteBandwidth = 5
	LteBandwidth_MHZ_20  LteBandwidth = 6
)

// Enum value maps for LteBandwidth.
var (
	LteBandwidth_name = map[int32]string{
		0: "UNKNOWN",
		1: "MHZ_1_4",
		2: "MHZ_3",
		3: "MHZ_5",
		4: "MHZ_10",
		5: "MHZ_15",
		6: "MHZ_20",
	}
	LteBandwidth_value = map[string]int32{
		"UNKNOWN": 0,
		"MHZ_1_4": 1,
		"MHZ_3":   2,
		"MHZ_5":   3,
		"MHZ_10":  4,
		"MHZ_15":  5,
		"MHZ_20":  6,
	}
)

func (x LteBandwidth) Enum() *LteBandwidth {
	p := new(LteBandwidth)
	*p = x
	return p
}

func (x LteBandwidth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LteBandwidth) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_enumTypes[0].Descriptor()
}

func (LteBandwidth) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_enumTypes[0]
}

func (x LteBandwidth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LteBandwidth.Descriptor instead.
func (LteBandwidth) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDesc = []byte{
	0x0a, 0x36, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x6c, 0x74, 0x65, 0x62, 0x61, 0x6e, 0x64, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x2f, 0x6c, 0x74, 0x65, 0x5f, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x22, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72,
	0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x6c, 0x74, 0x65, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x2a, 0x62, 0x0a, 0x0c,
	0x4c, 0x74, 0x65, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x48, 0x5a,
	0x5f, 0x31, 0x5f, 0x34, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x48, 0x5a, 0x5f, 0x33, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x48, 0x5a, 0x5f, 0x35, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06,
	0x4d, 0x48, 0x5a, 0x5f, 0x31, 0x30, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x48, 0x5a, 0x5f,
	0x31, 0x35, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x48, 0x5a, 0x5f, 0x32, 0x30, 0x10, 0x06,
	0x42, 0x30, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x50, 0x01, 0x5a, 0x15, 0x63, 0x72, 0x61,
	0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDescData = file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDesc
)

func file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDescData)
	})
	return file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDescData
}

var file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_goTypes = []any{
	(LteBandwidth)(0), // 0: com.craxiom.messaging.ltebandwidth.LteBandwidth
}
var file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_init() }
func file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_init() {
	if File_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto = out.File
	file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_rawDesc = nil
	file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_goTypes = nil
	file_com_craxiom_messaging_ltebandwidth_lte_bandwidth_proto_depIdxs = nil
}
