//*
// Defines the LTE NAS OTA Channel Type values used in the LTE NAS message.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/ltenaschanneltype/lte_nas_channel_type.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LteNasChannelType int32

const (
	LteNasChannelType_UNKNOWN    LteNasChannelType = 0
	LteNasChannelType_PLAIN      LteNasChannelType = 1
	LteNasChannelType_SEC_HEADER LteNasChannelType = 2
)

// Enum value maps for LteNasChannelType.
var (
	LteNasChannelType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PLAIN",
		2: "SEC_HEADER",
	}
	LteNasChannelType_value = map[string]int32{
		"UNKNOWN":    0,
		"PLAIN":      1,
		"SEC_HEADER": 2,
	}
)

func (x LteNasChannelType) Enum() *LteNasChannelType {
	p := new(LteNasChannelType)
	*p = x
	return p
}

func (x LteNasChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LteNasChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_enumTypes[0].Descriptor()
}

func (LteNasChannelType) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_enumTypes[0]
}

func (x LteNasChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LteNasChannelType.Descriptor instead.
func (LteNasChannelType) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDesc = []byte{
	0x0a, 0x42, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x6c, 0x74, 0x65, 0x6e, 0x61, 0x73, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x6c, 0x74, 0x65, 0x5f, 0x6e, 0x61,
	0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x27, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f,
	0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x6c, 0x74, 0x65, 0x6e,
	0x61, 0x73, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x3b, 0x0a,
	0x11, 0x4c, 0x74, 0x65, 0x4e, 0x61, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45,
	0x43, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x02, 0x42, 0x30, 0x0a, 0x15, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x50, 0x01, 0x5a, 0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDescData = file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDesc
)

func file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDescData)
	})
	return file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDescData
}

var file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_goTypes = []any{
	(LteNasChannelType)(0), // 0: com.craxiom.messaging.ltenaschanneltype.LteNasChannelType
}
var file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_init() }
func file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_init() {
	if File_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto = out.File
	file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_rawDesc = nil
	file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_goTypes = nil
	file_com_craxiom_messaging_ltenaschanneltype_lte_nas_channel_type_proto_depIdxs = nil
}
