//*
// Defines the Access Network Technology values used in the Phone State message.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/phonestate/networktype/network_type.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This enum defines the Access Network Technology field of the Phone State message.
//
// The values from this enum are taken directly from android.telephony.TelephonyManager#NETWORK_TYPES and should be kept
// in sync with those values. Even the numbers line up exactly, which makes conversion easier.
type NetworkType int32

const (
	NetworkType_UNKNOWN  NetworkType = 0
	NetworkType_GPRS     NetworkType = 1
	NetworkType_EDGE     NetworkType = 2
	NetworkType_UMTS     NetworkType = 3
	NetworkType_CDMA     NetworkType = 4
	NetworkType_EVDO_0   NetworkType = 5
	NetworkType_EVDO_A   NetworkType = 6
	NetworkType_OnexRTT  NetworkType = 7 // Had to replace the 1 with One
	NetworkType_HSDPA    NetworkType = 8
	NetworkType_HSUPA    NetworkType = 9
	NetworkType_HSPA     NetworkType = 10
	NetworkType_IDEN     NetworkType = 11
	NetworkType_EVDO_B   NetworkType = 12
	NetworkType_LTE      NetworkType = 13
	NetworkType_EHRPD    NetworkType = 14
	NetworkType_HSPAP    NetworkType = 15
	NetworkType_GSM      NetworkType = 16
	NetworkType_TD_SCDMA NetworkType = 17
	NetworkType_IWLAN    NetworkType = 18
	NetworkType_LTE_CA   NetworkType = 19
	NetworkType_NR       NetworkType = 20
)

// Enum value maps for NetworkType.
var (
	NetworkType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "GPRS",
		2:  "EDGE",
		3:  "UMTS",
		4:  "CDMA",
		5:  "EVDO_0",
		6:  "EVDO_A",
		7:  "OnexRTT",
		8:  "HSDPA",
		9:  "HSUPA",
		10: "HSPA",
		11: "IDEN",
		12: "EVDO_B",
		13: "LTE",
		14: "EHRPD",
		15: "HSPAP",
		16: "GSM",
		17: "TD_SCDMA",
		18: "IWLAN",
		19: "LTE_CA",
		20: "NR",
	}
	NetworkType_value = map[string]int32{
		"UNKNOWN":  0,
		"GPRS":     1,
		"EDGE":     2,
		"UMTS":     3,
		"CDMA":     4,
		"EVDO_0":   5,
		"EVDO_A":   6,
		"OnexRTT":  7,
		"HSDPA":    8,
		"HSUPA":    9,
		"HSPA":     10,
		"IDEN":     11,
		"EVDO_B":   12,
		"LTE":      13,
		"EHRPD":    14,
		"HSPAP":    15,
		"GSM":      16,
		"TD_SCDMA": 17,
		"IWLAN":    18,
		"LTE_CA":   19,
		"NR":       20,
	}
)

func (x NetworkType) Enum() *NetworkType {
	p := new(NetworkType)
	*p = x
	return p
}

func (x NetworkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_phonestate_networktype_network_type_proto_enumTypes[0].Descriptor()
}

func (NetworkType) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_phonestate_networktype_network_type_proto_enumTypes[0]
}

func (x NetworkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkType.Descriptor instead.
func (NetworkType) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_phonestate_networktype_network_type_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x2c, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x79, 0x70, 0x65, 0x2a,
	0xf2, 0x01, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x47, 0x50, 0x52, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x44, 0x47, 0x45, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x55, 0x4d, 0x54, 0x53, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x44,
	0x4d, 0x41, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x56, 0x44, 0x4f, 0x5f, 0x30, 0x10, 0x05,
	0x12, 0x0a, 0x0a, 0x06, 0x45, 0x56, 0x44, 0x4f, 0x5f, 0x41, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07,
	0x4f, 0x6e, 0x65, 0x78, 0x52, 0x54, 0x54, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x53, 0x44,
	0x50, 0x41, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x53, 0x55, 0x50, 0x41, 0x10, 0x09, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x53, 0x50, 0x41, 0x10, 0x0a, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x45,
	0x4e, 0x10, 0x0b, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x56, 0x44, 0x4f, 0x5f, 0x42, 0x10, 0x0c, 0x12,
	0x07, 0x0a, 0x03, 0x4c, 0x54, 0x45, 0x10, 0x0d, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x48, 0x52, 0x50,
	0x44, 0x10, 0x0e, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x53, 0x50, 0x41, 0x50, 0x10, 0x0f, 0x12, 0x07,
	0x0a, 0x03, 0x47, 0x53, 0x4d, 0x10, 0x10, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x44, 0x5f, 0x53, 0x43,
	0x44, 0x4d, 0x41, 0x10, 0x11, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x57, 0x4c, 0x41, 0x4e, 0x10, 0x12,
	0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x54, 0x45, 0x5f, 0x43, 0x41, 0x10, 0x13, 0x12, 0x06, 0x0a, 0x02,
	0x4e, 0x52, 0x10, 0x14, 0x42, 0x3b, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78,
	0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x50, 0x01, 0x5a, 0x15, 0x63, 0x72, 0x61, 0x78,
	0x69, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDescData = file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDesc
)

func file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDescData)
	})
	return file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDescData
}

var file_com_craxiom_messaging_phonestate_networktype_network_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_phonestate_networktype_network_type_proto_goTypes = []any{
	(NetworkType)(0), // 0: com.craxiom.messaging.phonestate.networktype.NetworkType
}
var file_com_craxiom_messaging_phonestate_networktype_network_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_phonestate_networktype_network_type_proto_init() }
func file_com_craxiom_messaging_phonestate_networktype_network_type_proto_init() {
	if File_com_craxiom_messaging_phonestate_networktype_network_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_phonestate_networktype_network_type_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_phonestate_networktype_network_type_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_phonestate_networktype_network_type_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_phonestate_networktype_network_type_proto = out.File
	file_com_craxiom_messaging_phonestate_networktype_network_type_proto_rawDesc = nil
	file_com_craxiom_messaging_phonestate_networktype_network_type_proto_goTypes = nil
	file_com_craxiom_messaging_phonestate_networktype_network_type_proto_depIdxs = nil
}
