//*
// Defines the Node Type values used in the 802.11 Survey message.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/wifi/nodetype/node_type.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_UNKNOWN    NodeType = 0
	NodeType_AP         NodeType = 1
	NodeType_NON_AP_STA NodeType = 2
	NodeType_STA        NodeType = 3
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "AP",
		2: "NON_AP_STA",
		3: "STA",
	}
	NodeType_value = map[string]int32{
		"UNKNOWN":    0,
		"AP":         1,
		"NON_AP_STA": 2,
		"STA":        3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_wifi_nodetype_node_type_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_wifi_nodetype_node_type_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_wifi_nodetype_node_type_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDesc = []byte{
	0x0a, 0x33, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x77, 0x69, 0x66, 0x69, 0x2f, 0x6e, 0x6f, 0x64,
	0x65, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69,
	0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x77, 0x69, 0x66,
	0x69, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x38, 0x0a, 0x08, 0x4e, 0x6f,
	0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x50, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4e,
	0x4f, 0x4e, 0x5f, 0x41, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x53,
	0x54, 0x41, 0x10, 0x03, 0x42, 0x35, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78,
	0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x77, 0x69,
	0x66, 0x69, 0x50, 0x01, 0x5a, 0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDescData = file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDesc
)

func file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDescData)
	})
	return file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDescData
}

var file_com_craxiom_messaging_wifi_nodetype_node_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_wifi_nodetype_node_type_proto_goTypes = []any{
	(NodeType)(0), // 0: com.craxiom.messaging.wifi.nodetype.NodeType
}
var file_com_craxiom_messaging_wifi_nodetype_node_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_wifi_nodetype_node_type_proto_init() }
func file_com_craxiom_messaging_wifi_nodetype_node_type_proto_init() {
	if File_com_craxiom_messaging_wifi_nodetype_node_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_wifi_nodetype_node_type_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_wifi_nodetype_node_type_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_wifi_nodetype_node_type_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_wifi_nodetype_node_type_proto = out.File
	file_com_craxiom_messaging_wifi_nodetype_node_type_proto_rawDesc = nil
	file_com_craxiom_messaging_wifi_nodetype_node_type_proto_goTypes = nil
	file_com_craxiom_messaging_wifi_nodetype_node_type_proto_depIdxs = nil
}
