//*
// Defines the SIM State values used in the Phone State message.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/phonestate/simstate/sim_state.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This enum defines the SIM State field of the Phone State message.
//
// The values from this enum are taken directly from android.telephony.TelephonyManager.SimState and should be kept in
// sync with those values. Even the numbers line up exactly, which makes conversion easier.
type SimState int32

const (
	SimState_UNKNOWN         SimState = 0
	SimState_ABSENT          SimState = 1
	SimState_PIN_REQUIRED    SimState = 2
	SimState_PUK_REQUIRED    SimState = 3
	SimState_NETWORK_LOCKED  SimState = 4
	SimState_READY           SimState = 5
	SimState_NOT_READY       SimState = 6
	SimState_PERM_DISABLED   SimState = 7
	SimState_CARD_IO_ERROR   SimState = 8
	SimState_CARD_RESTRICTED SimState = 9
	SimState_LOADED          SimState = 10
	SimState_PRESENT         SimState = 11
)

// Enum value maps for SimState.
var (
	SimState_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "ABSENT",
		2:  "PIN_REQUIRED",
		3:  "PUK_REQUIRED",
		4:  "NETWORK_LOCKED",
		5:  "READY",
		6:  "NOT_READY",
		7:  "PERM_DISABLED",
		8:  "CARD_IO_ERROR",
		9:  "CARD_RESTRICTED",
		10: "LOADED",
		11: "PRESENT",
	}
	SimState_value = map[string]int32{
		"UNKNOWN":         0,
		"ABSENT":          1,
		"PIN_REQUIRED":    2,
		"PUK_REQUIRED":    3,
		"NETWORK_LOCKED":  4,
		"READY":           5,
		"NOT_READY":       6,
		"PERM_DISABLED":   7,
		"CARD_IO_ERROR":   8,
		"CARD_RESTRICTED": 9,
		"LOADED":          10,
		"PRESENT":         11,
	}
)

func (x SimState) Enum() *SimState {
	p := new(SimState)
	*p = x
	return p
}

func (x SimState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimState) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_enumTypes[0].Descriptor()
}

func (SimState) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_enumTypes[0]
}

func (x SimState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimState.Descriptor instead.
func (SimState) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_phonestate_simstate_sim_state_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDesc = []byte{
	0x0a, 0x39, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2f, 0x73, 0x69, 0x6d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x73, 0x69, 0x6d, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x63, 0x6f, 0x6d,
	0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x73, 0x69,
	0x6d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0xc9, 0x01, 0x0a, 0x08, 0x53, 0x69, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x42, 0x53, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c,
	0x50, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x02, 0x12, 0x10,
	0x0a, 0x0c, 0x50, 0x55, 0x4b, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x4c, 0x4f, 0x43, 0x4b,
	0x45, 0x44, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x05, 0x12,
	0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x06, 0x12, 0x11,
	0x0a, 0x0d, 0x50, 0x45, 0x52, 0x4d, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10,
	0x07, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x49, 0x4f, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x08, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x52, 0x45, 0x53,
	0x54, 0x52, 0x49, 0x43, 0x54, 0x45, 0x44, 0x10, 0x09, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x4f, 0x41,
	0x44, 0x45, 0x44, 0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45, 0x53, 0x45, 0x4e, 0x54,
	0x10, 0x0b, 0x42, 0x3b, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f,
	0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x50, 0x01, 0x5a, 0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f,
	0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDescData = file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDesc
)

func file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDescData)
	})
	return file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDescData
}

var file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_goTypes = []any{
	(SimState)(0), // 0: com.craxiom.messaging.phonestate.simstate.SimState
}
var file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_init() }
func file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_init() {
	if File_com_craxiom_messaging_phonestate_simstate_sim_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_phonestate_simstate_sim_state_proto = out.File
	file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_rawDesc = nil
	file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_goTypes = nil
	file_com_craxiom_messaging_phonestate_simstate_sim_state_proto_depIdxs = nil
}
