//*
// Defines the Standard values used in the 802.11 Survey message.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/wifi/standard/standard.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Standard int32

const (
	Standard_UNKNOWN     Standard = 0
	Standard_IEEE80211   Standard = 1
	Standard_IEEE80211A  Standard = 2
	Standard_IEEE80211B  Standard = 3
	Standard_IEEE80211G  Standard = 4
	Standard_IEEE80211BG Standard = 5
	Standard_IEEE80211N  Standard = 6
	Standard_IEEE80211AC Standard = 7
	Standard_IEEE80211AX Standard = 8
	Standard_IEEE80211BE Standard = 9
)

// Enum value maps for Standard.
var (
	Standard_name = map[int32]string{
		0: "UNKNOWN",
		1: "IEEE80211",
		2: "IEEE80211A",
		3: "IEEE80211B",
		4: "IEEE80211G",
		5: "IEEE80211BG",
		6: "IEEE80211N",
		7: "IEEE80211AC",
		8: "IEEE80211AX",
		9: "IEEE80211BE",
	}
	Standard_value = map[string]int32{
		"UNKNOWN":     0,
		"IEEE80211":   1,
		"IEEE80211A":  2,
		"IEEE80211B":  3,
		"IEEE80211G":  4,
		"IEEE80211BG": 5,
		"IEEE80211N":  6,
		"IEEE80211AC": 7,
		"IEEE80211AX": 8,
		"IEEE80211BE": 9,
	}
)

func (x Standard) Enum() *Standard {
	p := new(Standard)
	*p = x
	return p
}

func (x Standard) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Standard) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_wifi_standard_standard_proto_enumTypes[0].Descriptor()
}

func (Standard) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_wifi_standard_standard_proto_enumTypes[0]
}

func (x Standard) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Standard.Descriptor instead.
func (Standard) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_wifi_standard_standard_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_wifi_standard_standard_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_wifi_standard_standard_proto_rawDesc = []byte{
	0x0a, 0x32, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x77, 0x69, 0x66, 0x69, 0x2f, 0x73, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f,
	0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x77, 0x69, 0x66, 0x69,
	0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x2a, 0xaa, 0x01, 0x0a, 0x08, 0x53, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32, 0x31, 0x31,
	0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32, 0x31, 0x31, 0x41,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32, 0x31, 0x31, 0x42,
	0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32, 0x31, 0x31, 0x47,
	0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32, 0x31, 0x31, 0x42,
	0x47, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32, 0x31, 0x31,
	0x4e, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32, 0x31, 0x31,
	0x41, 0x43, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32, 0x31,
	0x31, 0x41, 0x58, 0x10, 0x08, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x45, 0x45, 0x45, 0x38, 0x30, 0x32,
	0x31, 0x31, 0x42, 0x45, 0x10, 0x09, 0x42, 0x35, 0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72,
	0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x77, 0x69, 0x66, 0x69, 0x50, 0x01, 0x5a, 0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_wifi_standard_standard_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_wifi_standard_standard_proto_rawDescData = file_com_craxiom_messaging_wifi_standard_standard_proto_rawDesc
)

func file_com_craxiom_messaging_wifi_standard_standard_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_wifi_standard_standard_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_wifi_standard_standard_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_wifi_standard_standard_proto_rawDescData)
	})
	return file_com_craxiom_messaging_wifi_standard_standard_proto_rawDescData
}

var file_com_craxiom_messaging_wifi_standard_standard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_wifi_standard_standard_proto_goTypes = []any{
	(Standard)(0), // 0: com.craxiom.messaging.wifi.standard.Standard
}
var file_com_craxiom_messaging_wifi_standard_standard_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_wifi_standard_standard_proto_init() }
func file_com_craxiom_messaging_wifi_standard_standard_proto_init() {
	if File_com_craxiom_messaging_wifi_standard_standard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_wifi_standard_standard_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_wifi_standard_standard_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_wifi_standard_standard_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_wifi_standard_standard_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_wifi_standard_standard_proto = out.File
	file_com_craxiom_messaging_wifi_standard_standard_proto_rawDesc = nil
	file_com_craxiom_messaging_wifi_standard_standard_proto_goTypes = nil
	file_com_craxiom_messaging_wifi_standard_standard_proto_depIdxs = nil
}
