//*
// Defines the Technology values used for this Bluetooth Survey message. This is not the same as the technologies
// supported by the device, but instead just the specific technology used to send the packet that this survey record
// represents.
//
// This protobuf definition is provided as a convenience only. See the official API documentation for the true field
// schema.
//
// It is necessary to define this enum in an individual file so that duplicate enum values can be used. This file
// specifies a different protobuf package than other enums so that the enum value scope is different than all other
// enums.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: com/craxiom/messaging/bluetooth/tech/technology.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Technology int32

const (
	Technology_UNKNOWN Technology = 0
	Technology_BR_EDR  Technology = 1 // Basic Rate / Enhanced Data Rate (also covers 802.11 AMP). Aka Classic.
	Technology_LE      Technology = 2
)

// Enum value maps for Technology.
var (
	Technology_name = map[int32]string{
		0: "UNKNOWN",
		1: "BR_EDR",
		2: "LE",
	}
	Technology_value = map[string]int32{
		"UNKNOWN": 0,
		"BR_EDR":  1,
		"LE":      2,
	}
)

func (x Technology) Enum() *Technology {
	p := new(Technology)
	*p = x
	return p
}

func (x Technology) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Technology) Descriptor() protoreflect.EnumDescriptor {
	return file_com_craxiom_messaging_bluetooth_tech_technology_proto_enumTypes[0].Descriptor()
}

func (Technology) Type() protoreflect.EnumType {
	return &file_com_craxiom_messaging_bluetooth_tech_technology_proto_enumTypes[0]
}

func (x Technology) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Technology.Descriptor instead.
func (Technology) EnumDescriptor() ([]byte, []int) {
	return file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDescGZIP(), []int{0}
}

var File_com_craxiom_messaging_bluetooth_tech_technology_proto protoreflect.FileDescriptor

var file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDesc = []byte{
	0x0a, 0x35, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74,
	0x68, 0x2f, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61,
	0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x62,
	0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x2a, 0x2d, 0x0a,
	0x0a, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x52, 0x5f, 0x45,
	0x44, 0x52, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x3a, 0x0a, 0x1f,
	0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x62, 0x6c, 0x75, 0x65, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x50,
	0x01, 0x5a, 0x15, 0x63, 0x72, 0x61, 0x78, 0x69, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDescOnce sync.Once
	file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDescData = file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDesc
)

func file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDescGZIP() []byte {
	file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDescOnce.Do(func() {
		file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDescData = protoimpl.X.CompressGZIP(file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDescData)
	})
	return file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDescData
}

var file_com_craxiom_messaging_bluetooth_tech_technology_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_craxiom_messaging_bluetooth_tech_technology_proto_goTypes = []any{
	(Technology)(0), // 0: com.craxiom.messaging.bluetooth.tech.Technology
}
var file_com_craxiom_messaging_bluetooth_tech_technology_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_craxiom_messaging_bluetooth_tech_technology_proto_init() }
func file_com_craxiom_messaging_bluetooth_tech_technology_proto_init() {
	if File_com_craxiom_messaging_bluetooth_tech_technology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_craxiom_messaging_bluetooth_tech_technology_proto_goTypes,
		DependencyIndexes: file_com_craxiom_messaging_bluetooth_tech_technology_proto_depIdxs,
		EnumInfos:         file_com_craxiom_messaging_bluetooth_tech_technology_proto_enumTypes,
	}.Build()
	File_com_craxiom_messaging_bluetooth_tech_technology_proto = out.File
	file_com_craxiom_messaging_bluetooth_tech_technology_proto_rawDesc = nil
	file_com_craxiom_messaging_bluetooth_tech_technology_proto_goTypes = nil
	file_com_craxiom_messaging_bluetooth_tech_technology_proto_depIdxs = nil
}
